"""Fix user authentication system

Revision ID: b5dcf76b4290
Revises: e3576b2b0b11
Create Date: 2025-09-03 10:30:53.076268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5dcf76b4290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('circulating_supply', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_supply', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('max_supply', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('price_change_percentage_24h', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('price_change_percentage_7d', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('price_change_percentage_30d', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('ath', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('ath_date', sa.DateTime(), nullable=True),
    sa.Column('atl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('atl_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('whitepaper', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_coins', 'cryptocurrencies', ['is_active', 'market_cap_rank'], unique=False)
    op.create_index('idx_last_updated', 'cryptocurrencies', ['last_updated'], unique=False)
    op.create_index('idx_market_cap', 'cryptocurrencies', ['market_cap'], unique=False)
    op.create_index('idx_market_cap_rank', 'cryptocurrencies', ['market_cap_rank'], unique=False)
    op.create_index('idx_price_change_24h', 'cryptocurrencies', ['price_change_percentage_24h'], unique=False)
    op.create_index('idx_total_volume', 'cryptocurrencies', ['total_volume'], unique=False)
    op.create_index(op.f('ix_cryptocurrencies_id'), 'cryptocurrencies', ['id'], unique=False)
    op.create_index(op.f('ix_cryptocurrencies_slug'), 'cryptocurrencies', ['slug'], unique=True)
    op.create_index(op.f('ix_cryptocurrencies_symbol'), 'cryptocurrencies', ['symbol'], unique=True)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_volume', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crypto_timestamp', 'price_history', ['cryptocurrency_id', 'timestamp'], unique=False)
    op.create_index('idx_price_history_lookup', 'price_history', ['symbol', 'timestamp', 'price'], unique=False)
    op.create_index('idx_symbol_timestamp', 'price_history', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_history_cryptocurrency_id'), 'price_history', ['cryptocurrency_id'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'TRADER', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_id'), 'risk_alerts', ['id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('volatility_score', sa.Float(), nullable=False),
    sa.Column('liquidity_score', sa.Float(), nullable=False),
    sa.Column('market_cap_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('confidence_interval', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('calculation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_window_days', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_table('trading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('starting_balance', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl_percentage', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('max_balance', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('min_balance', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('max_drawdown', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('sharpe_ratio', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_sessions_id'), 'trading_sessions', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usd_balance', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_invested', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_profit_loss', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_portfolio_value', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('daily_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('max_drawdown', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('win_rate', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('average_buy_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('current_value', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl_percentage', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('first_purchase_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT', name='ordertype'), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('executed_quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('executed_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'CANCELLED', 'PARTIAL', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('stop_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('trigger_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('fee_percentage', sa.DECIMAL(precision=8, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl_percentage', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_trading_sessions_id'), table_name='trading_sessions')
    op.drop_table('trading_sessions')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_risk_alerts_id'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_cryptocurrency_id'), table_name='price_history')
    op.drop_index('idx_symbol_timestamp', table_name='price_history')
    op.drop_index('idx_price_history_lookup', table_name='price_history')
    op.drop_index('idx_crypto_timestamp', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_cryptocurrencies_symbol'), table_name='cryptocurrencies')
    op.drop_index(op.f('ix_cryptocurrencies_slug'), table_name='cryptocurrencies')
    op.drop_index(op.f('ix_cryptocurrencies_id'), table_name='cryptocurrencies')
    op.drop_index('idx_total_volume', table_name='cryptocurrencies')
    op.drop_index('idx_price_change_24h', table_name='cryptocurrencies')
    op.drop_index('idx_market_cap_rank', table_name='cryptocurrencies')
    op.drop_index('idx_market_cap', table_name='cryptocurrencies')
    op.drop_index('idx_last_updated', table_name='cryptocurrencies')
    op.drop_index('idx_active_coins', table_name='cryptocurrencies')
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###